# This policy allows outgoing network traffic from worker nodes in each zone
# of your cluster to the cluster master through the private service endpoint.
# Note that you must allow outgoing traffic for all of the zones within the region.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-private-service-endpoint
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # Nets for US East
      - 166.9.20.11
      - 166.9.22.8
      - 166.9.20.12
      - 166.9.20.13
      - 166.9.22.9
      - 166.9.22.10
      - 166.9.24.4
      - 166.9.24.5
      ports:
      - 20000:32767
      - 443
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for US East
      - 166.9.20.11
      - 166.9.22.8
      - 166.9.20.12
      - 166.9.20.13
      - 166.9.22.9
      - 166.9.22.10
      - 166.9.24.4
      - 166.9.24.5
      ports:
      - 20000:32767
      - 443
    protocol: TCP
    source: {}
  order: 1900
  selector: ibm.role == 'worker_private'
  types:
  - Egress
